name: flutter_task
description: "A new Flutter project."

publish_to: 'none'

# The version of the application.
version: 1.0.0+1

environment:
  sdk: ^3.10.4

# Application dependencies.
dependencies:
  flutter:
    sdk: flutter

  intl: ^0.20.2
  cupertino_icons: ^1.0.8

  # UI & Animations
  flutter_screenutil: ^5.9.3
  flutter_native_splash: ^2.4.7
  cached_network_image: ^3.4.1
  scrollable_positioned_list: ^0.3.8
  google_fonts: ^8.0.2
  flutter_svg: ^2.2.3
  toastification: ^3.0.3
  skeletonizer: ^2.1.3
  gap: ^3.0.1

  # State Management & Utilities
  flutter_bloc: ^9.1.1
  flutter_hooks: ^0.21.3+1
  get_it: ^9.2.1
  equatable: ^2.0.8
  dartz: ^0.10.1
  logger: ^2.6.2

  # Helpers & Services
  intl_phone_number_input: ^0.7.5
  dropdown_textfield: ^1.2.0

  # Navigation
  go_router: ^17.1.0

  # Networking & Storage
  dio: ^5.9.2
  hive_flutter: ^1.1.0
  hive: ^2.2.3

dependency_overrides:
  intl: ^0.20.2

# Dependencies for development and testing.
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  rename_app: ^1.6.5
  change_app_package_name: ^1.5.0
  flutter_launcher_icons: ^0.14.4


# Configuration for the app's launcher icons.
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_foreground: "assets/icons/app_icon.png"
  adaptive_icon_background: "#FFFFFF"


# Configuration for the app's native splash screen.
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/icons/splash_icon.png

  android_12:
    color: "#FFFFFF"
    image: assets/icons/splash_icon.png
    icon_background_color: "#FFFFFF"

  fullscreen: true
  android: true
  ios: true



# Flutter-specific configuration.
flutter:
  uses-material-design: true

  # Asset declarations.
  assets:
    - assets/icons/
    - assets/images/
